# Generated by Django 4.2 on 2024-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_stripe_product_price_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products_images"),
        ),
    ]
